version: '3'
services:
  db:
    image: postgres:15
    container_name: banners_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: banners_redis

  banners:
    image: banners_image
    build:
      context: .
    container_name: banners_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/banners/docker/app.sh"]
    ports:
      - 7777:8000
